import { csvEscape, purchasePrice, type ExportAdapter } from "./base";

export const sortSwiftAdapter: ExportAdapter = {
  key: "sortswift",
  label: "Sort Swift",
  filenameSlug: "sortswift",
  groupBy: "card-foil",
  games: "all",
  headers: () => [
    "skuId",
    "tcgplayerId",
    "scryfallId",
    "cardtraderId",
    "cardmarketId",
    "productId",
    "cardTitle",
    "productName",
    "rowNumber",
    "condition",
    "condAbbr",
    "language",
    "langAbbr",
    "printing",
    "quantity",
    "price",
    "cost",
    "comment",
    "remarks",
    "cdn_link",
    "cdn_back_link",
  ],
  row: ({ card, quantity, isFoil }, ctx) => [
    "",
    "",
    ctx.isMtg ? card.id : "",
    "",
    "",
    "",
    csvEscape(card.name),
    csvEscape(card.name),
    "",
    "NM",
    "NM",
    "EN",
    "EN",
    isFoil ? "Holofoil" : "Normal",
    String(quantity),
    purchasePrice(card, isFoil),
    "0",
    "",
    "",
    card.image?.normal ?? "",
    "",
  ],
};
