export const LANGUAGE_LABELS: Record<string, string> = {
  en: "English",
  de: "German",
  ja: "Japanese",
  fr: "French",
  es: "Spanish",
  it: "Italian",
  pt: "Portuguese",
  "pt-br": "Portuguese (Brazil)",
  "pt-pt": "Portuguese (Portugal)",
  ru: "Russian",
  "zh-tw": "Chinese (Traditional)",
  "zh-cn": "Chinese (Simplified)",
  ko: "Korean",
  nl: "Dutch",
  id: "Indonesian",
  th: "Thai",
  lo: "Lao",
  zht: "Chinese (Traditional)",
  zhs: "Chinese (Simplified)",
};
