import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Field, FieldError, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { localPost } from "@/lib/auth/local-api";
import { zodResolver } from "@hookform/resolvers/zod";
import { IconLoader2 } from "@tabler/icons-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { useTranslation } from "react-i18next";
import { useNavigate, useSearchParams } from "react-router-dom";
import { z } from "zod";

const schema = z
  .object({
    password: z.string().min(8),
    confirmPassword: z.string(),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"],
  });

// Local-mode only - the link generated by LocalEmailProvider's password
// reset email points here. resetPassword() also revokes every other active
// session for the account (own-auth's own behavior), so this always sends
// the user to sign in fresh with their new password rather than trying to
// keep them logged in.
export default function AuthResetPasswordPage() {
  const { t } = useTranslation("auth");
  const [searchParams] = useSearchParams();
  const token = searchParams.get("token");
  const navigate = useNavigate();
  const [serverError, setServerError] = useState<string | null>(null);

  const form = useForm<z.infer<typeof schema>>({
    resolver: zodResolver(schema),
    defaultValues: { password: "", confirmPassword: "" },
  });

  async function onSubmit({ password }: z.infer<typeof schema>) {
    if (!token) return;
    setServerError(null);
    try {
      const res = await localPost<{ success: boolean; message?: string }>(
        "/api/local-auth/reset-password",
        { token, newPassword: password },
      );
      if (!res.success) {
        setServerError(res.message ?? t("local.resetPasswordFailed"));
        return;
      }
      navigate("/auth/sign-in", { replace: true });
    } catch {
      setServerError(t("local.joinUnreachable"));
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-muted p-4">
      <Card className="w-full max-w-sm">
        <CardHeader>
          <CardTitle>{t("local.resetPasswordTitle")}</CardTitle>
          <CardDescription>
            {!token
              ? t("local.resetPasswordInvalid")
              : t("local.resetPasswordDescription")}
          </CardDescription>
        </CardHeader>
        {token && (
          <CardContent>
            <form
              id="reset-password-form"
              onSubmit={form.handleSubmit(onSubmit)}
              className="flex flex-col gap-3"
            >
              <Field data-invalid={!!form.formState.errors.password}>
                <FieldLabel htmlFor="password">
                  {t("local.newPasswordLabel")}
                </FieldLabel>
                <Input
                  id="password"
                  type="password"
                  autoComplete="new-password"
                  autoFocus
                  {...form.register("password")}
                />
                <FieldError errors={[form.formState.errors.password]} />
              </Field>
              <Field data-invalid={!!form.formState.errors.confirmPassword}>
                <FieldLabel htmlFor="confirmPassword">
                  {t("local.confirmPasswordLabel")}
                </FieldLabel>
                <Input
                  id="confirmPassword"
                  type="password"
                  autoComplete="new-password"
                  {...form.register("confirmPassword")}
                />
                <FieldError errors={[form.formState.errors.confirmPassword]} />
              </Field>
              {serverError && (
                <p className="text-xs text-destructive">{serverError}</p>
              )}
            </form>
          </CardContent>
        )}
        {token && (
          <CardFooter>
            <Button
              type="submit"
              form="reset-password-form"
              className="w-full"
              disabled={form.formState.isSubmitting}
            >
              {form.formState.isSubmitting && (
                <IconLoader2 className="animate-spin" />
              )}
              {t("local.resetPasswordSubmit")}
            </Button>
          </CardFooter>
        )}
      </Card>
    </div>
  );
}
